#!/bin/bash
#
# Example panel for lemonbar

get() {
    echo -n $2 | sed -e "s/.*$1 \(\w*\).*/\1/"
}

. ~/.config/bar/panel_colors

while read -r line ; do
    case $line in
        D*)
            # clock output
            currDate="%{F$COLOR_TITLE_FG}${line#?}%{B-}%{F-}"
            ;;
        T*)
            # clock output
            currTime=" %{F$COLOR_TITLE_FG}${line#?}%{B-}%{F-} "
            ;;
        M*)
            mpd=" ${line#?}%{B-}%{F-}"
            ;;
        W*)
            wm_infos="${line#?}"
            ;;
    esac
    printf "%s\n" "%{l}${wm_infos}%{c}${mpd}%{r}${currDate}${currTime}"
done
