#!/bin/bash
#
# Example panel for lemonbar

get() {
    echo -n $2 | sed -e "s/.*$1 \(\w*\).*/\1/"
}

. ~/.config/bar/panel_colors

while read -r line ; do
    case $line in
        D*)
            # clock output
            currDate="%{F$COLOR_DATE}${line#?}%{B-}%{F-}"
            ;;
        B*)
            # battery output
            status=$(get 'status' "${line#?}")
            power=$(get 'power' "${line#?}")

            battery="%{B$COLOR_DEFAULT_BG}"

            if [[ $status -ge 100 ]]; then
                battery=$battery"%{F$COLOR_BATT_FULL}  "
            elif [[ $status -ge 75 && $status -lt 100 ]]; then
                battery=$battery"%{F$COLOR_BATT_HIGH} $status% %{B$COLOR_DEFAULT_BG}"
            elif [[ $status -ge 50 && $status -lt 75 ]]; then
                battery=$battery"%{F$COLOR_BATT_LOW} $status% %{B$COLOR_DEFAULT_BG}"
            elif [[ $status -ge 25 && $status -lt 50 ]]; then
                battery=$battery"%{F$COLOR_BATT_LOW} $status% %{B$COLOR_DEFAULT_BG}"
            elif [[ $status -lt 25 ]]; then
                battery=$battery"%{F$COLOR_BATT_CRIT} $status% %{B$COLOR_DEFAULT_BG}"
            fi

            if [[ $power == "Charging" ]]; then
                battery=$battery"%{F$COLOR_YELLOW} "
            fi

            ;;
        T*)
            # clock output
            currTime=" %{F$COLOR_CLOCK}${line#?}%{B-}%{F-} "
            ;;
        M*)
            mpd=" ${line#?}%{B-}%{F-}"
            ;;
        W*)
            wm_infos="${line#?}"
            ;;
    esac
    printf "%s\n" "%{l}${wm_infos}%{c}${mpd}%{r}${battery}${currDate}${currTime}"
done
