#!/bin/bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4   # Use the super key as the main modifier

hc keybind Mod1-Control-Delete quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc spawn xsetroot -cursor_name left_ptr &
hc spawn unclutter &
hc spawn setxkbmap -option ctrl:nocaps &
hc spawn bash -c "([[ -f $HOME/.Xresources && -r ~/.Xresources ]] && xrdb -merge  $HOME/.Xresources) &" &
hc spawn anamnesis --start &
hc spawn mpd --start &
hc spawn sleep 2 && nitrogen --restore &
hc spawn killall compton && sleep 1 && compton -CGb
hc spawn sleep 2 && mpd

#Custom Key Bindings
hc keybind $Mod-Return spawn termite -e zsh -c "tmux -q has-session && exec tmux attach-session -d || exec tmux new-session -n$USER -s$USER@$HOSTNAME"
hc keybind $Mod-d spawn rofi -font "Hack 10" -show run -matching fuzzy

#Fn Multimedia Bindings
hc keybind XF86AudioPlay spawn ~/.config/herbstluftwm/audio_handle/audio.sh toggle

hc keybind XF86AudioPrev spawn ~/.config/herbstluftwm/audio_handle/audio.sh prev
hc keybind XF86AudioNext spawn ~/.config/herbstluftwm/audio_handle/audio.sh next
hc keybind XF86AudioRaiseVolume spawn amixer -q sset Master 3%+
hc keybind XF86AudioLowerVolume spawn amixer -q sset Master 3%-
hc keybind XF86AudioMute spawn amixer -q sset Master toggle

hc keybind XF86MonBrightnessUp spawn light -A 1
hc keybind XF86MonBrightnessDown spawn light -U 1

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#f8f6f2'
hc set frame_border_normal_color '#1c1c1c'
hc set frame_bg_normal_color '#565656'
# orange
hc set frame_bg_active_color '#FF8533'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 18

hc attr theme.active.color '#83a598'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color '#1c1c1c'
hc attr theme.border_width 0
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color '#1c1c1c'
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#1c1c1c'

hc set window_gap 2
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule class=termite tag=1 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole|termite)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# find the panel
#panel=~/.config/bar/panel
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
"$panel" &
#done

hc spawn killall trayer && sleep 2 && bash -c "trayer --edge bottom --SetDockType true --transparent true --widthtype request --align center --height 18 --alpha 255 --tint 0x000000 --transparent true &"
